# Generated by Django 5.1.1 on 2024-09-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='build',
            options={'ordering': ['hero__name', '-id']},
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['id']},
        ),
        migrations.AddField(
            model_name='hero',
            name='img',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
