# Generated by Django 5.1.1 on 2024-09-12 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0002_alter_build_options_alter_hero_options_hero_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
