# Generated by Django 5.1.1 on 2024-09-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0004_alter_hero_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='hero',
            name='attribute',
            field=models.CharField(choices=[('STR', 'Strength'), ('AG', 'Agility'), ('INT', 'Intelligence'), ('UNI', 'Universal')], default='UNI', max_length=3),
        ),
        migrations.AlterField(
            model_name='hero',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Build',
        ),
    ]
