# Generated by Django 5.1.1 on 2024-09-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0006_alter_hero_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='items')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='hero',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='heroes'),
        ),
    ]
