# Generated by Django 5.1.1 on 2024-09-15 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0008_alter_item_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('is_left', models.BooleanField()),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.hero')),
            ],
            options={
                'ordering': ['hero', 'id'],
            },
        ),
    ]
