# Generated by Django 5.1.1 on 2024-09-15 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0009_talent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('max_points', models.SmallIntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='skills')),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.hero')),
            ],
            options={
                'ordering': ['hero', 'name'],
            },
        ),
    ]
