# Generated by Django 5.1.1 on 2024-09-15 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0010_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='TalentWrapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explanation', models.TextField(blank=True)),
                ('talent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.talent')),
            ],
        ),
    ]
