# Generated by Django 5.1.1 on 2024-09-15 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0013_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('skills', models.ManyToManyField(to='default_dota_app.skill')),
            ],
        ),
    ]
