# Generated by Django 5.1.1 on 2024-09-15 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0014_skillbuild'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guide_title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='hero',
            options={'ordering': ['hero_name']},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ['hero', 'skill_name']},
        ),
        migrations.RenameField(
            model_name='hero',
            old_name='name',
            new_name='hero_name',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='description',
            new_name='skill_description',
        ),
        migrations.RenameField(
            model_name='skill',
            old_name='name',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='stage',
            old_name='name',
            new_name='stage_name',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='item_wrappers',
        ),
        migrations.AddField(
            model_name='itemwrapper',
            name='order',
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='itemwrapper',
            name='stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.stage'),
        ),
        migrations.AddField(
            model_name='skillbuild',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.guide'),
        ),
        migrations.AddField(
            model_name='stage',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.guide'),
        ),
        migrations.AddField(
            model_name='talentwrapper',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='default_dota_app.guide'),
        ),
    ]
