# Generated by Django 5.1.1 on 2024-09-15 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0015_guide_alter_hero_options_alter_item_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillbuild',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillbuilds', to='default_dota_app.guide'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='default_dota_app.guide'),
        ),
        migrations.AlterField(
            model_name='talentwrapper',
            name='guide',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='talentwrappers', to='default_dota_app.guide'),
        ),
    ]
