# Generated by Django 5.1.1 on 2024-09-15 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0016_alter_skillbuild_guide_alter_stage_guide_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='description',
            new_name='item_description',
        ),
    ]
