# Generated by Django 5.1.1 on 2024-09-16 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0019_alter_itemwrapper_stage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talentwrapper',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='skillbuild',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='stage',
            name='guide',
        ),
        migrations.RemoveField(
            model_name='itemwrapper',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemwrapper',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='skillbuild',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='talent',
            name='hero',
        ),
        migrations.RemoveField(
            model_name='talentwrapper',
            name='talent',
        ),
        migrations.DeleteModel(
            name='Guide',
        ),
        migrations.DeleteModel(
            name='ItemWrapper',
        ),
        migrations.DeleteModel(
            name='Stage',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
        migrations.DeleteModel(
            name='SkillBuild',
        ),
        migrations.DeleteModel(
            name='Talent',
        ),
        migrations.DeleteModel(
            name='TalentWrapper',
        ),
    ]
