# Generated by Django 5.1.1 on 2024-09-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0021_guide_stage_itemwrapper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='guide_description',
            field=models.TextField(blank=True),
        ),
    ]
