# Generated by Django 5.1.1 on 2024-09-16 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0022_alter_guide_guide_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemwrapper',
            name='item_wrapper_explanation',
            field=models.TextField(blank=True),
        ),
    ]
