# Generated by Django 5.1.1 on 2024-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0024_alter_itemwrapper_stage_alter_stage_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(choices=[('STRENGTH', 'Strength'), ('AGILITY', 'Agility'), ('INTELLIGENCE', 'Intelligence'), ('UNIVERSAL', 'Universal')], default='UNIVERSAL', max_length=20)),
                ('img', models.ImageField(blank=True, null=True, upload_to='attributes')),
            ],
        ),
    ]
