# Generated by Django 5.1.1 on 2024-09-21 12:33

import django.db.models.deletion
from django.db import migrations, models


def migrate_attributes_to_fk(apps, schema_editor):
    Hero = apps.get_model('default_dota_app', 'Hero')
    Attribute = apps.get_model('default_dota_app', 'Attribute')

    for hero in Hero.objects.all():
        if hero.attribute_str_tmp:
            attribute, created = Attribute.objects.get_or_create(attribute_name=hero.attribute_str_tmp)
            hero.attribute = attribute
            hero.save()


class Migration(migrations.Migration):
    dependencies = [
        ('default_dota_app', '0025_attribute'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hero',
            old_name='attribute',
            new_name='attribute_str_tmp'
        ),

        migrations.AddField(
            model_name='hero',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='default_dota_app.attribute'),
        ),

        migrations.RunPython(migrate_attributes_to_fk),

        migrations.RemoveField(
            model_name='hero',
            name='attribute_str_tmp'
        )
    ]
