# Generated by Django 5.1.1 on 2024-09-22 08:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0026_alter_hero_attribute'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=300)),
                ('skill_description', models.TextField(blank=True)),
                ('max_points', models.IntegerField(default=4, validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(1)])),
                ('img', models.ImageField(blank=True, null=True, upload_to='skills')),
                ('skill_order', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(4)])),
                ('hero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills', to='default_dota_app.hero')),
            ],
            options={
                'ordering': ['hero__hero_name', 'skill_order'],
            },
        ),
    ]
