# Generated by Django 5.1.1 on 2024-09-22 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0027_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='skill_order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(6), django.core.validators.MinValueValidator(1)]),
        ),
    ]
