# Generated by Django 5.1.1 on 2024-09-22 10:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0028_alter_skill_skill_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillBuild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_build_name', models.CharField(max_length=300)),
                ('skill_build_description', models.TextField(blank=True)),
                ('display_order', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_builds', to='default_dota_app.guide')),
            ],
        ),
        migrations.CreateModel(
            name='SkillOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='default_dota_app.skill')),
                ('skill_build', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_orders', to='default_dota_app.skillbuild')),
            ],
        ),
    ]
