# Generated by Django 5.1.1 on 2024-09-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0030_skillorder_learning_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='skillbuild',
            name='skill_build_name',
        ),
    ]
