# Generated by Django 5.1.1 on 2024-09-22 11:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


# def reorder_attributes(apps, schema_editor):
#     Attribute = apps.get_model('default_dota_app', 'Attribute')
#     Attribute.reorder()


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0032_skillbuild_skill_build_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['display_order']},
        ),
        migrations.AddField(
            model_name='attribute',
            name='display_order',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='skillorder',
            name='skill_build',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skills_order', to='default_dota_app.skillbuild'),
        ),

        # migrations.RunPython(reorder_attributes)
    ]
