# Generated by Django 5.1.1 on 2024-09-25 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0037_alter_attribute_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['display_order']},
        ),
    ]
