# Generated by Django 5.1.1 on 2024-09-25 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0039_guide_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hero',
            name='hero_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
