# Generated by Django 5.1.1 on 2024-09-25 16:37

import django.core.validators
from django.db import migrations, models

import default_dota_app.models.guide_model


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0041_alter_guide_options_guide_display_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='skillbuild',
            options={'ordering': ['guide__hero__hero_name', 'guide__display_order', 'display_order']},
        ),
        migrations.AlterField(
            model_name='guide',
            name='display_order',
            field=models.IntegerField(default=default_dota_app.models.guide_model.get_next_guide_order, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
