# Generated by Django 5.1.1 on 2024-10-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0045_itemsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsection',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='item_sections'),
        ),
    ]
