# Generated by Django 5.1.1 on 2024-10-01 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0046_itemsection_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='default_dota_app.itemsection'),
        ),
    ]
