# Generated by Django 5.1.1 on 2024-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default_dota_app', '0048_alter_itemsection_section_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='attribute_name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
